### ISSUE TITLE
09 -- Calculator -- Elizabeth Elliott

### ISSUE THREAD

**Issue by Za1006** [TheIronYard--Orlando/2015--FALL--iOS#100]
#### Storyboard Tasks

* [x] Build UI with buttons for each operand and operator and include a label to display the input from the user.
* [x] Apply autolayout rules to all UI elements to make sure they are responsive and will fit within the bounds of the device's screen.
* [x] Connect all UI elements to either IBOutlets or IBActions as necessary.

#### Code Tasks

* [x] Create IBActions for each operand and operator button so you can respond whenever the user taps a button.
* [x] Create a class called CalculatorBrain to hold state information about the current calculation. An object of this type will be created and destroyed as each "calculation transaction" is performed by the user.
* [ ] As the user enters information, redirect the operands and operators to the CalculatorBrain class so when they tap the _=_ button, the brain will be ready to perform the calculation.
* [ ] Perform the calculation and return an answer to the view controller for display on-screen.

#### Journal, Week 1

* [x] The journal is due on Monday, so please finish up your edits and only add a link to the PR to today's issue once you have completed it. Also, have 1 other person in-class read through the entry and provide feedback to you in your PR. When they comment, it will attach their GH username so we'll be able to see who you picked.

#### Kata 2
Due next Wednesday, Oct 21st.

**Comment by Za1006** [comment]
https://github.com/Za1006/Za1006.github.io/tree/journal-week-1

**Comment by Za1006** [comment]
https://github.com/Za1006/Za1006.github.io/wiki/journal-week-1

**Comment by jholsapple** [comment]
Didn't see much code in your repo. Try to get some code on the screen

**Comment by Za1006** [comment]
added code into project
