### ISSUE TITLE
09 -- Calculator -- Pedro Trujillo

### ISSUE THREAD

**Issue by PedroTrujilloV** [TheIronYard--Orlando/2015--FALL--iOS#102]
Create a single view application that shows a calculator interface. It should have buttons for numbers 0 - 9 (plus a . button so you can add floating point numbers) as well as 7 operator buttons (addition, subtraction, multiplication, division, and equals, plus/minus, percent). It should also have a button to clear out the current transaction (clear). It will need a label to display the current value of the calculator. It should operate as you would expect from a normal calculator. You can open the Apple-provided calculator app on your iOS device to get an idea of the appropriate layout.

#### Storyboard Tasks

* [x] Build UI with buttons for each operand and operator and include a label to display the input from the user.
* [x] Apply autolayout rules to all UI elements to make sure they are responsive and will fit within the bounds of the device's screen.
* [x] Connect all UI elements to either IBOutlets or IBActions as necessary.

#### Code Tasks

* [x] Create IBActions for each operand and operator button so you can respond whenever the user taps a button.
* [x] Create a class called CalculatorBrain to hold state information about the current calculation. An object of this type will be created and destroyed as each "calculation transaction" is performed by the user.
* [x] As the user enters information, redirect the operands and operators to the CalculatorBrain class so when they tap the _=_ button, the brain will be ready to perform the calculation.
* [x] Perform the calculation and return an answer to the view controller for display on-screen.

#### Journal, Week 1

* [x] The journal is due on Monday, so please finish up your edits and only add a link to the PR to today's issue once you have completed it. Also, have 1 other person in-class read through the entry and provide feedback to you in your PR. When they comment, it will attach their GH username so we'll be able to see who you picked.

#### Kata 2
Due next Wednesday, Oct 21st.

**Comment by PedroTrujilloV** [comment]
https://github.com/PedroTrujilloV/TIY-Assignments/tree/master/09--If-My-Calculations-Are-Correct/

**Comment by PedroTrujilloV** [comment]
https://github.com/PedroTrujilloV/PedroTrujilloV.github.io/pull/3

**Comment by PedroTrujilloV** [comment]
https://github.com/PedroTrujilloV/TIY-Assignments/tree/master/09--If-My-Calculations-Are-Correct/Kata2.playground

**Comment by PedroTrujilloV** [comment]
if you guys forgot check the kata1 this is the link: 

https://github.com/PedroTrujilloV/TIY-Assignments/tree/master/01--Great-Scott/Kata1.playground

**Comment by jholsapple** [comment]
Good job, Pedro!

**Comment by PedroTrujilloV** [comment]
thanks!
