### ISSUE TITLE
11 -- The Grail Diary -- Isaiah Khan

### ISSUE THREAD

**Issue by CodeKhan01** [TheIronYard--Orlando/2015--FALL--iOS#104]
#### Normal Mode

* [x] Create a model class and add appropriate attributes
* [x] Create a JSON file to use for your input data
* [x] Read in the JSON file in the view controller and create a model object for each record.
* [x] Display the name and one of the attributes in the cell
* [ ] Create a second view controller that will display all the site data when a cell is tapped.

#### Hard Mode

* [ ] Create a custom cell class and add UI elements to display the various properties from the model
* [ ] Modify the view controller to use the custom cell

#### Journal, Week 2

* [x] Create a branch in your github.io repo and a file called ```journal-week-2.md```
* [x] Create a pull request from this branch back to master on the github.io repo
* [x] Add link to this pull request on this day's homework issue in the class repo

#### Kata 2

* [ ] Continue to work on the second set of kata problems. They are due on Wednesday.

**Comment by CodeKhan01** [comment]
https://github.com/CodeKhan01/TIY-Assignments/pull/3

**Comment by jholsapple** [comment]
Keep at it. Try to get this figured out. You're going to do a bunch with custom cells

**Comment by CodeKhan01** [comment]
Pull Request link:
https://github.com/CodeKhan01/CodeKhan01.github.io/pull/2

Wiki Link:
https://github.com/CodeKhan01/CodeKhan01.github.io/wiki/journal-week-2
