### ISSUE TITLE
11 -- The Grail Diary -- Samuel Shaw

### ISSUE THREAD

**Issue by SamuelShaw** [TheIronYard--Orlando/2015--FALL--iOS#105]
#### Normal Mode

* [X] Create a model class and add appropriate attributes
* [X] Create a JSON file to use for your input data
* [X] Read in the JSON file in the view controller and create a model object for each record.
* [X] Display the name and one of the attributes in the cell
* [X] Create a second view controller that will display all the site data when a cell is tapped.

#### Hard Mode

* [ ] Create a custom cell class and add UI elements to display the various properties from the model
* [ ] Modify the view controller to use the custom cell

#### Journal, Week 2

* [ ] Create a branch in your github.io repo and a file called ```journal-week-2.md```
* [ ] Create a pull request from this branch back to master on the github.io repo
* [ ] Add link to this pull request on this day's homework issue in the class repo

#### Kata 2

* [ ] Continue to work on the second set of kata problems. They are due on Wednesday.

**Comment by jholsapple** [comment]
Make sure you're committing your work properly. I don't see a project to grade. 

The label is red until you can commit a project to be graded.

**Comment by SamuelShaw** [comment]
https://github.com/SamuelShaw/TIY-Assignments/pull/6
