### ISSUE TITLE
11 -- The Grail Diary -- Jen Hamilton

### ISSUE THREAD

**Issue by embryoconcepts** [TheIronYard--Orlando/2015--FALL--iOS#107]
### Normal Mode

Create a single view application that shows at least 10 famous historical sites around the world in a tableview. Create a model class called Site that can model three attributes as properties. Build this app in the same manner that we've used so far in class. So start with the most trivial implementation of the tableview and build from there, one step at a time.

[Info on JSON syntax](https://en.wikipedia.org/wiki/JSON#Data_types.2C_syntax_and_example). Contains an example as well.

### Hard Mode

Once you have an application that can display each site in a tableviewcell and show one of the attributes from the model object, create a custom cell class and set it up to display the name and the three properties from the model.

#### Normal Mode

* [x] Create a model class and add appropriate attributes
* [x] Create a JSON file to use for your input data
* [x] Read in the JSON file in the view controller and create a model object for each record.
* [x] Display the name and one of the attributes in the cell
* [x] Create a second view controller that will display all the site data when a cell is tapped.

#### Hard Mode

* [x] Create a custom cell class and add UI elements to display the various properties from the model
* [x] Modify the view controller to use the custom cell

#### Journal, Week 2

* [x] Create a branch in your github.io repo and a file called ```journal-week-2.md```
* [x] Create a pull request from this branch back to master on the github.io repo
* [x] Add link to this pull request on this day's homework issue in the class repo

#### Kata 2

* [x] Continue to work on the second set of kata problems. They are due on Wednesday.

**Comment by embryoconcepts** [comment]
Kata complete: https://github.com/embryoconcepts/Code-Katas/tree/master/Kata2.playground

**Comment by embryoconcepts** [comment]
Journal week 2: https://github.com/embryoconcepts/embryoconcepts.github.io/pull/3

**Comment by embryoconcepts** [comment]
Project PR: https://github.com/embryoconcepts/TIY-Assignments/pull/11

**Comment by jholsapple** [comment]
Good job!
