### ISSUE TITLE
00 -- This is Heavy -- David Johnson

### ISSUE THREAD

**Issue by daaavid** [TheIronYard--Orlando/2015--FALL--iOS#11]
### Tasks:

* [X] [Create a Github account](https://github.com/signup)
* [X] Find and star [the class project](https://github.com/TheIronYard--Orlando/2015--FALL--iOS)
* [x] Read [the Home page on the class wiki](https://github.com/TheIronYard--Orlando/2015--FALL--iOS/wiki)
* [x] [Create a new _WIP Issue_](https://github.com/TheIronYard--Orlando/2015--FALL--iOS/issues/new)
  * [x] Named `00 -- This is Heavy -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  * [x] With this checklist as the description
* [x] [Edit your Github profile](https://github.com/settings/profile) to provide:
  * [x] A picture, so I can recognize your face.
  * [x] Your full name, so I can recognize your name.
  * [x] A valid public email address, so I can contact you if I need to.
* [x] [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/)
  * [x] Add a link to your new Github repo as a comment on your *WIP Issue*
* [x] Complete the Code School course [Try Git](https://www.codeschool.com/courses/try-git)
  * [x] Take a screenshot of the Try Git course when you complete it and add it as a comment to your *WIP Issue*
* [x] Create a new repository called `TIY-Assignments`
  * [x] Check the box to create an initial `README.md` file
  * [x] Select the `CC0` -- "Creative Commons" license for your work
  * [x] Add a link to your `TIY-Assignments` repo as a comment on your *WIP Issue*
* [x] Install Xcode from the Mac App Store. Simply search for _Xcode_.
* [x] Open Xcode. Click the _Xcode_ menu in the menubar, then choose _Preferences_. Navigate to the _Downloads_ tab and install the latest iOS documentation (currently iOS 8.3, will probably be 9.0 when class starts). Once fully downloaded, the docset should have a small checkmark next to it.
* [x] Watch _The Long Run_ Videos on [Delve.tv](http://delve.tv)
   * [x] [_The Long Game_, part 1](http://delve.tv/the-long-game-part-one/)
   * [x] [_The Long Game_, part 2](http://delve.tv/the-long-game-part-2/)
* [x] Complete the [Swift Basics](http://teamtreehouse.com/library/swift-basics) course on Treehouse.
   * [x] Take a screenshot of your points earned for the course and add it as a comment to your *WIP Issue*
* [x] Look at the Prework-A file for instructions on how to complete the Counter app.
   * [x] Your counter app files should be added to your TIY-Assignments repo. Because you previously added a link to your repo to your *WIP Issue*, I will be able to see your progress as you go. Be sure to commit/push the changes you make as you work on the app.

**Comment by abyssteus** [comment]
https://github.com/abyssteus/hello-world

**Comment by abyssteus** [comment]
<img width="1680" alt="screen shot 2015-10-01 at 5 17 34 pm" src="https://cloud.githubusercontent.com/assets/9387285/10234077/65e0f82a-6860-11e5-8989-3740cbd4176e.png">

**Comment by abyssteus** [comment]
https://github.com/abyssteus/TIY-Assignments

**Comment by abyssteus** [comment]
<img width="1680" alt="screenshot 2015-10-03 07 41 42" src="https://cloud.githubusercontent.com/assets/9387285/10262732/5be751b4-69a2-11e5-897f-ed377352b243.png">

**Comment by jcgohlke** [comment]
Good job. Please review and close.
