### ISSUE TITLE
11-- The Grail Diary -- Keron Williams

### ISSUE THREAD

**Issue by kdw9** [TheIronYard--Orlando/2015--FALL--iOS#112]
#### Normal Mode

* [x] Create a model class and add appropriate attributes
* [x] Create a JSON file to use for your input data
* [x] Read in the JSON file in the view controller and create a model object for each record.
* [x] Display the name and one of the attributes in the cell
* [ ] Create a second view controller that will display all the site data when a cell is tapped.

#### Hard Mode

* [x] Create a custom cell class and add UI elements to display the various properties from the model
* [x] Modify the view controller to use the custom cell

#### Journal, Week 2

* [x] Create a branch in your github.io repo and a file called ```journal-week-2.md```
* [x] Create a pull request from this branch back to master on the github.io repo
* [x] Add link to this pull request on this day's homework issue in the class repo

#### Kata 2

* [x] Continue to work on the second set of kata problems. They are due on Wednesday.

**Comment by kdw9** [comment]
https://github.com/kdw9/kdw9.github.io/pull/2

**Comment by jholsapple** [comment]
Good job! Keep at it. 

Remember to do a pull request for your project too.
