### ISSUE TITLE
12 -- In Due Time -- Juan Burgos

### ISSUE THREAD

**Issue by juanburgos** [TheIronYard--Orlando/2015--FALL--iOS#120]
Homework PR:

https://github.com/juanburgos/TIY-Assignments/pull/8

#### Normal Mode

* [x] Create a project with the Core Data box checked
* [x] Define your entity and attributes in the data model file
* [x] Create an NSManagedObject subclass of your entity
* [x] Create a custom cell design to show the todo item description and checkbox
* [x] Create a custom cell class to use with your prototype cell and add IBOutlets for your cell's subviews
* [x] Configure the TableViewController to show 1 cell to test your cell's design
* [x] Add code to your TableViewController to allow the user to enter data in the UITextField and hide the keyboard when they press enter
* [x] Add a + UIBarButtonItem to the upper right of the navbar
* [x] Add an IBAction that will create a new managed todoitem object
* [x] In cellForRowAtIndexPath, add logic that will show the keyboard if the todoitem's description is empty
* [x] Intercept when the user presses "return" after entering a description and update the todoitem managed object
    * [x] Also be sure to save the managedObjectContext so the change is written to disk
* [x] Create todoitems, quit the app and on relaunch make sure the items return
* [x] Create an IBAction to update the todoitem's status when the checkbox is tapped
    * [ ] Be sure to save the context after you update the managed object
* [ ] In the commitEditingStyle function, add logic that will only allow the cell to be deleted if the todoitem has been checked off. Consult the item's completed Boolean.

#### Hard Mode

* [ ] Make a few checklist items to describe how to implement the hard mode

#### Journal, Week 2

* [x] Continue work on your journal entry

#### Kata 2

* [x] Continue to work on the second set of kata problems. They are due on Wednesday.

**Comment by jholsapple** [comment]
Good!
