### ISSUE TITLE
12 -- In Due Time -- Pedro Trujillo

### ISSUE THREAD

**Issue by PedroTrujilloV** [TheIronYard--Orlando/2015--FALL--iOS#124]
#### Normal Mode

* [x] Create a project with the Core Data box checked
* [x] Define your entity and attributes in the data model file
* [x] Create an NSManagedObject subclass of your entity
* [x] Create a custom cell design to show the todo item description and checkbox
* [x] Create a custom cell class to use with your prototype cell and add IBOutlets for your cell's subviews
* [x] Configure the TableViewController to show 1 cell to test your cell's design
* [x] Add code to your TableViewController to allow the user to enter data in the UITextField and hide the keyboard when they press enter
* [x] Add a + UIBarButtonItem to the upper right of the navbar
* [x] Add an IBAction that will create a new managed todoitem object
* [x] In cellForRowAtIndexPath, add logic that will show the keyboard if the todoitem's description is empty
* [x] Intercept when the user presses "return" after entering a description and update the todoitem managed object
    * [x] Also be sure to save the managedObjectContext so the change is written to disk
* [x] Create todoitems, quit the app and on relaunch make sure the items return
* [x] Create an IBAction to update the todoitem's status when the checkbox is tapped
    * [x] Be sure to save the context after you update the managed object
* [x] In the commitEditingStyle function, add logic that will only allow the cell to be deleted if the todoitem has been checked off. Consult the item's completed Boolean.

#### Hard Mode

* [x] Make a few checklist items to describe how to implement the hard mode:
    * [x] Create a ViewController in the storyboard
    * [x] Add an date picker to that view controller
    * [x] connect your object in the table view controller to the new view controller
    * [x] Create a new .swift  file for the new view controller
    * [x] Implement delegators to send or get data from the date picker 
    * [x] Save the date and be sure that it is loading when you open your app

#### Journal, Week 2

* [x] Continue work on your journal entry

#### Kata 2

* [x] Continue to work on the second set of kata problems. They are due on Wednesday.

**Comment by PedroTrujilloV** [comment]
Journal Week 2
https://github.com/PedroTrujilloV/PedroTrujilloV.github.io/pull/4

**Comment by PedroTrujilloV** [comment]
Homework Assignment 
https://github.com/PedroTrujilloV/TIY-Assignments/tree/master/12--The-Temple-of-Core-Data/InDueTime

**Comment by PedroTrujilloV** [comment]
Again Kata 2 if was not checked 

https://github.com/PedroTrujilloV/TIY-Assignments/tree/master/09--If-My-Calculations-Are-Correct/Kata2.playground

**Comment by PedroTrujilloV** [comment]
For this app, you can delete directly in the cell, or you can check  the switch the task cell in off and it will erase it automatically when the app is executed again, loading only the on tasks in the list.
Also you can set the due date taping in the "set due date: MM/dd/YY" button.

**Comment by jholsapple** [comment]
Good job!

**Comment by PedroTrujilloV** [comment]
thanks!
