### ISSUE TITLE
14 -- HighVoltage -- Jen Hamilton

### ISSUE THREAD

**Issue by embryoconcepts** [TheIronYard--Orlando/2015--FALL--iOS#130]
#### Synopsis

Let's build a universal app for Doc so he can perform those crucial calculations on the fly. The main view will be a tableview with dynamically added cells, one for each value type. The + button will create a popover when tapped to allow the user to select the value type they want to add. Once two values are entered, the app should disable the + button and perform the necessary calculations to add the two remaining value types to the screen. The clear button will empty the table and prepare the app for a new transaction.

See [this site](http://www.rapidtables.com/calc/electric/watt-volt-amp-calculator.htm) for the list of equations as well as a web implementation of this app you can use for testing

#### Normal Mode
* [x] Design your cells in the storyboard and see if you can get one of each on the screen
* [x] Create the view controller in the storyboard that will show each of the types (the one you'll use as a popover.
* [x] Make the app show the types view as a modal when you tap the + button
* [x] Switch the presentation style to a popover
* [x] Implement the popoverpresentationcontroller delegate methods to ensure the view appears as a popover
* [x] Create a class to perform all the calculations
* [x] ... [add additional steps here]

#### Journal, Week 2

* [x] Continue work on your journal entry. Due on Monday. Have 1 other classmate read it over before you turn it in. Create a pull request against your branch and have the proofreader add a comment to the PR to indicate they've read it.

#### Kata 3

* [x] Continue working on kata 3. Due next Wednesday.

**Comment by embryoconcepts** [comment]
High Voltage PR: https://github.com/embryoconcepts/TIY-Assignments/pull/13
Journal 2: https://github.com/embryoconcepts/embryoconcepts.github.io/pull/3
Kata 3: https://github.com/embryoconcepts/Code-Katas

**Comment by jholsapple** [comment]
Good job!
