### ISSUE TITLE
14 -- High Voltage -- Chris Stomp

### ISSUE THREAD

**Issue by stomp1128** [TheIronYard--Orlando/2015--FALL--iOS#131]
#### Normal Mode

* [x] Design your cells in the storyboard and see if you can get one of each on the screen
* [x] Create the view controller in the storyboard that will show each of the types (the one you'll use as a popover.
* [x] Make the app show the types view as a modal when you tap the + button
* [x] Switch the presentation style to a popover
* [x] Implement the popoverpresentationcontroller delegate methods to ensure the view appears as a popover
* [x] Create a class to perform all the calculations
* [ ] ... [add additional steps here]

#### Journal, Week 2

* [x] Continue work on your journal entry. Due on Monday. Have 1 other classmate read it over before you turn it in. Create a pull request against your branch and have the proofreader add a comment to the PR to indicate they've read it.

#### Kata 3

* [x] Continue working on kata 3. Due next Wednesday.

**Comment by stomp1128** [comment]
https://github.com/stomp1128/TIY-Assignments/pull/8

**Comment by jholsapple** [comment]
Good job!
