### ISSUE TITLE
14 -- High Voltage -- Pedro Trujillo

### ISSUE THREAD

**Issue by PedroTrujilloV** [TheIronYard--Orlando/2015--FALL--iOS#133]
#### Normal Mode

* [x] Design your cells in the storyboard and see if you can get one of each on the screen
* [x] Create the view controller in the storyboard that will show each of the types (the one you'll use as a popover.
* [x] Make the app show the types view as a modal when you tap the + button
* [x] Switch the presentation style to a popover
* [x] Implement the popoverpresentationcontroller delegate methods to ensure the view appears as a popover

* [x] Create a class called CalculatorBrain to hold state information about the current calculation. An object of this type will be created and destroyed as each "calculation transaction" is performed by the user.
* [x] As the user enters information, redirect the operands and operators to the CalculatorBrain class so when they tap the popover and chose any option, with that task it will calculate the result for the the last two variables.
* [x] Perform the calculation and return an answer to the view controller for display on-screen.

#### Journal, Week 2

* [x] Continue work on your journal entry. Due on Monday. Have 1 other classmate read it over before you turn it in. Create a pull request against your branch and have the proofreader add a comment to the PR to indicate they've read it.

#### Kata 3

* [x] Continue working on kata 3. Due next Wednesday.

**Comment by PedroTrujilloV** [comment]
https://github.com/PedroTrujilloV/TIY-Assignments/tree/master/14--A-New-HIG/High%20Voltage

**Comment by PedroTrujilloV** [comment]
kata 3 
https://github.com/PedroTrujilloV/TIY-Assignments/tree/master/13--The-Last-Playlist/Kata3.playground

**Comment by PedroTrujilloV** [comment]
https://github.com/PedroTrujilloV/PedroTrujilloV.github.io/pull/4

**Comment by jholsapple** [comment]
Good job!

**Comment by PedroTrujilloV** [comment]
thanks!
