### ISSUE TITLE
01 -- Great Scott! -- Jen Hamilton

### ISSUE THREAD

**Issue by embryoconcepts** [TheIronYard--Orlando/2015--FALL--iOS#14]
### Shaving the Weekly Yak
* [x] Complete the repo-related tasks for your weekly journal (see below). (S)
* [x] Commit and push your Counter app prework to your TIY-Assignments folder. (S)
* [x] Begin research on The Right Mindset. (M)
* [x] Complete either an outline or (very) rough draft of your essay and place in your journal repo's wiki. (M)
* [x] Work on your first set of Coding Kata exercises. (L)

**Comment by embryoconcepts** [comment]
Wiki page: https://github.com/embryoconcepts/embryoconcepts.github.io/wiki/The-Right-Mindset

**Comment by jcgohlke** [comment]
Good job. Please review and close.
