### ISSUE TITLE
01 -- Great Scott! -- David Johnson

### ISSUE THREAD

**Issue by daaavid** [TheIronYard--Orlando/2015--FALL--iOS#15]
### Shaving the Weekly Yak
* [x] Complete the repo-related tasks for your weekly journal.
* [x] Commit and push your Counter app prework to your TIY-Assignments folder.
* [x] Begin research on The Right Mindset.
* [x] Complete either an outline or (very) rough draft of your essay and place in your journal repo's wiki.
* [x] Work on your first set of Coding Kata exercises.

**Comment by daaavid** [comment]
https://github.com/daaavid/daaavid.github.io/wiki/The-Right-Mindset

**Comment by jcgohlke** [comment]
Good job. Please review and close.
