### ISSUE TITLE
16 -- TackyTacTac -- Samuel Shaw

### ISSUE THREAD

**Issue by SamuelShaw** [TheIronYard--Orlando/2015--FALL--iOS#155]
HW Pull Request:

https://github.com/SamuelShaw/TIY-Assignments/pull/3

#### Normal Mode

* [ ] Add functionality to allow the user to reset the board
* [ ] Add functionality to show the score of each player (how many games won)
* [x] Update gameStatusLabel for each player's turn, and also notify the user when a player has one
* [ ] Add functionality to randomly choose from several different colors for each player so each game shows different sets of game board colors

#### Journal, Week 2

* [ ] Find some concept we have already learned about and write a tutorial about it. It could be a framework or set of classes in the iOS SDK, or some concept from Swift we've used in class or in homework. For tonight, just perform some research about which concept you'd like to cover and maybe make some bullet points on the major areas you'd like to cover in your tutorial.

#### Kata 3

* [X] Continue working on kata 3. Due Wednesday.

**Comment by jholsapple** [comment]
Make multiple commits to show history and progress
