### ISSUE TITLE
01--Great Scott! --Chris Stomp

### ISSUE THREAD

**Issue by stomp1128** [TheIronYard--Orlando/2015--FALL--iOS#16]
### Shaving the Weekly Yak
* [x] Complete the repo-related tasks for your weekly journal (see below).
* [x] Commit and push your Counter app prework to your TIY-Assignments folder.
* [x] Begin research on The Right Mindset.
* [x] Complete either an outline or (very) rough draft of your essay and place in your journal repo's wiki.
* [x] Work on your first set of Coding Kata exercises.

**Comment by stomp1128** [comment]
https://github.com/stomp1128/stomp1128.github.io/wiki/The-Right-Mindset/_edit

**Comment by jcgohlke** [comment]
Good job. Please review and close.
