### ISSUE TITLE
01 -- Great Scott! -- Michael Reynolds

### ISSUE THREAD

**Issue by MTR2D2** [TheIronYard--Orlando/2015--FALL--iOS#17]
### Shaving the Weekly Yak
* [x] Complete the repo-related tasks for your weekly journal (see below).
* [x] Commit and push your Counter app prework to your TIY-Assignments folder.
* [x] Begin research on The Right Mindset.
* [x] Complete either an outline or (very) rough draft of your essay and place in your journal repo's wiki.
* [x] Work on your first set of Coding Kata exercises.

**Comment by MTR2D2** [comment]
https://github.com/MTR2D2/USERNAME.github.io/wiki/The-Right-Mindset

**Comment by jcgohlke** [comment]
Good job. Please review and close.
