### ISSUE TITLE
01 -- Great Scott! -- Phillip English

### ISSUE THREAD

**Issue by PhillipEnglish** [TheIronYard--Orlando/2015--FALL--iOS#18]
### Shaving the Weekly Yak
* [x] Complete the repo-related tasks for your weekly journal (see below).
* [x] Commit and push your Counter app prework to your TIY-Assignments folder.
* [x] Begin research on The Right Mindset.
* [x] Complete either an outline or (very) rough draft of your essay and place in your journal repo's wiki.
* [x] Work on your first set of Coding Kata exercises.

**Comment by PhillipEnglish** [comment]
https://github.com/PhillipEnglish/PhillipEnglish.github.io

**Comment by jcgohlke** [comment]
Good job. Please review and close.
