### ISSUE TITLE
01 -- Great Scott! -- Pedro Trujillo

### ISSUE THREAD

**Issue by PedroTrujilloV** [TheIronYard--Orlando/2015--FALL--iOS#19]
### Shaving the Weekly Yak
* [x] Complete the repo-related tasks for your weekly journal (see below).
* [x] Commit and push your Counter app prework to your TIY-Assignments folder.
* [x] Begin research on The Right Mindset.
* [x] Complete either an outline or (very) rough draft of your essay and place in your journal repo's wiki.
* [x] Work on your first set of Coding Kata exercises.

**Comment by PedroTrujilloV** [comment]
Journal, Week One: The Right Mindset

Create a new repository called USERNAME.github.io where USERNAME is your GitHub username, e.g. https://github.com/jcgohlke/jcgohlke.github.io/ Select the CC0 license and elect to create a README file for the repository. Create a page in the wiki for your repo called The Right Mindset.

Research The Growth Mindsets by Dr. Carol Dweck, starting with the videos provided below. Document your sources on your wiki page, targeting a short (3 - 5 paragraphs) journal entry that includes all of the following:

summarizes the two mindsets and characteristics of each
either describes a personal situation in which you experienced each mindset or describes which aspects of each mindset you recognize in yourself
explains how you will apply this understanding to your experience at The Iron Yard
If you need guidance, follow the writing process: start by brainstorming some ideas about the topic and write an outline of your essay, no more than three levels deep, on your wiki page. Otherwise, you can start with your first Rough Draft -- very unorganized, stream of consciousness.

This assignment will be due on Thursday, but we'll review everyone's work so far in class on Tuesday. Be sure to link your wiki page in your WIP Issue!

Videos for The Growth Mindset

You can learn anything on Khan Academy
The Power of Yet by Dr. Carol Dweck on TED
Carol Dweck, Growth Mindsets and Motivation on TED-ed

**Comment by PedroTrujilloV** [comment]
## This is the link to the Wiki 'The-Right-Mindset':

https://github.com/PedroTrujilloV/PedroTrujilloV.github.io/wiki/The-Right-Mindset

**Comment by jcgohlke** [comment]
Good job. Please review and close.

**Comment by PedroTrujilloV** [comment]
https://github.com/PedroTrujilloV/TIY-Assignments/tree/master/01--Great-Scott/Kata1.playground

thanks!
