### ISSUE TITLE
00 -- This is Heavy -- JEN HAMILTON

### ISSUE THREAD

**Issue by embryoconcepts** [TheIronYard--Orlando/2015--FALL--iOS#2]
### Tasks:

* [X] [Create a Github account](https://github.com/signup)
* [X] Find and star [the class project](https://github.com/TheIronYard--Orlando/2015--FALL--iOS)
* [x] Read [the Home page on the class wiki](https://github.com/TheIronYard--Orlando/2015--FALL--iOS/wiki)
* [x] [Create a new _WIP Issue_](https://github.com/TheIronYard--Orlando/2015--FALL--iOS/issues/new)
  * [x] Named `00 -- This is Heavy -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  * [x] With this checklist as the description
* [x] [Edit your Github profile](https://github.com/settings/profile) to provide:
  * [x] A picture, so I can recognize your face.
  * [x] Your full name, so I can recognize your name.
  * [x] A valid public email address, so I can contact you if I need to.
* [x] [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/)
  * [x] Add a link to your new Github repo as a comment on your *WIP Issue*
* [x] Complete the Code School course [Try Git](https://www.codeschool.com/courses/try-git)
  * [x] Take a screenshot of the Try Git course when you complete it and add it as a comment to your *WIP Issue*
* [x] Create a new repository called `TIY-Assignments`
  * [x] Check the box to create an initial `README.md` file
  * [x] Select the `CC0` -- "Creative Commons" license for your work
  * [x] Add a link to your `TIY-Assignments` repo as a comment on your *WIP Issue*
* [x] Install Xcode from the Mac App Store. Simply search for _Xcode_.
* [x] Open Xcode. Click the _Xcode_ menu in the menubar, then choose _Preferences_. Navigate to the _Downloads_ tab and install the latest iOS documentation (currently iOS 8.3, will probably be 9.0 when class starts). Once fully downloaded, the docset should have a small checkmark next to it.
* [x] Watch _The Long Run_ Videos on [Delve.tv](http://delve.tv)
   * [x] [_The Long Game_, part 1](http://delve.tv/the-long-game-part-one/)
   * [x] [_The Long Game_, part 2](http://delve.tv/the-long-game-part-2/)
* [x] Complete the [Swift Basics](http://teamtreehouse.com/library/swift-basics) course on Treehouse.
   * [x] Take a screenshot of your points earned for the course and add it as a comment to your *WIP Issue*
* [x] Look at the Prework-A file for instructions on how to complete the Counter app.
   * [x] Your counter app files should be added to your TIY-Assignments repo. Because you previously added a link to your repo to your *WIP Issue*, I will be able to see your progress as you go. Be sure to commit/push the changes you make as you work on the app.

**Comment by embryoconcepts** [comment]
Github's Hello World tutorial repo: https://github.com/embryoconcepts/hello-world

**Comment by embryoconcepts** [comment]
CodeSchool Git courses (previously had a paid account)

![screen shot 2015-09-23 at 5 06 19 pm](https://cloud.githubusercontent.com/assets/1554169/10058820/726d99fa-6215-11e5-8b53-c8b30f7c5951.png)

Full report card: https://www.codeschool.com/users/467695

**Comment by embryoconcepts** [comment]
TIY-Assignments Repo: https://github.com/embryoconcepts/TIY-Assignments

**Comment by embryoconcepts** [comment]
Treehouse Swift Basics course screenshot: 

![screen shot 2015-09-24 at 7 27 47 pm](https://cloud.githubusercontent.com/assets/1554169/10089496/6babd0a4-62f2-11e5-9af2-a23295e4bbf6.png)

**Comment by embryoconcepts** [comment]
Re: Counter assignment. 

Can you please clarify whether you want us to fork or clone the project to our own machine, then push to our TIY Assignments repo?

**Comment by embryoconcepts** [comment]
Notes on completing Prework A: 
- Cloned *This is Heavy* repo to computer
- Copied _just_ the Controller folder to TIY Assignments folder
- Opened Counter.xcodeproj
- Converted to current Swift syntax (running Xcode 7)

**Comment by embryoconcepts** [comment]
Errors on Prework A identified as an issue stemming from allowing Xcode to convert to latest version of Swift. I recreated the project in another folder successfully, just by opting not to convert. When I copied those files into the Counter folder, Xcode was still giving errors. Renaming the folder to Counter2 is a temporary solution. (tldr: DO NOT CONVERT TO LATEST SWIFT)

In addition, it was necessary to change the file structure slightly, as Xcode was unable to find the Info.plist.

**Comment by jcgohlke** [comment]
Jen,

Thanks for taking a deep dive into trying to fix the Counter app. I wrote it with Swift 1.2 and Xcode 6. It appears the Swift 2 converter is not working as well as it should. I'll take a look and probably just update it for Swift 2.

Sorry it was a bit of a slog. Great job on all the prework! Cloning the class repo to your machine is fine. You will mostly be creating new projects in your own TIY-Assignments repo to push the work back to GitHub, as your access to the class repo is read-only.

**Comment by jcgohlke** [comment]
Made some changes to the Counter app to fix the issues you encountered. Thanks for debugging! Please close this issue.
