### ISSUE TITLE
01--Great-Scott -- Isaiah Khan

### ISSUE THREAD

**Issue by CodeKhan01** [TheIronYard--Orlando/2015--FALL--iOS#20]
### Shaving the Weekly Yak
* [x] Complete the repo-related tasks for your weekly journal (see below).
* [x] Commit and push your Counter app prework to your TIY-Assignments folder.
* [x] Begin research on The Right Mindset.
* [x] Complete either an outline or (very) rough draft of your essay and place in your journal repo's wiki.
* [ ] Work on your first set of Coding Kata exercises.

**Comment by jcgohlke** [comment]
I don't see your outline or rough draft in your journal repo wiki. Did you put it somewhere else?

**Comment by CodeKhan01** [comment]
I am going to submit it now, did not type it in the repo, just did a quick draft on Pages.

**Comment by CodeKhan01** [comment]
https://github.com/CodeKhan01/CodeKhan01.github.io.wiki.git

**Comment by CodeKhan01** [comment]
Just submitted my rough draft and commented the link!

**Comment by CodeKhan01** [comment]
https://github.com/CodeKhan01/CodeKhan01.github.io/wiki/The-Right-Mindset
