### ISSUE TITLE
01 -- Great Scott! -- Keron Williams

### ISSUE THREAD

**Issue by kdw9** [TheIronYard--Orlando/2015--FALL--iOS#21]
### Shaving the Weekly Yak
* [x] Complete the repo-related tasks for your weekly journal (see below).
* [x] Commit and push your Counter app prework to your TIY-Assignments folder.
* [x] Begin research on The Right Mindset.
* [x] Complete either an outline or (very) rough draft of your essay and place in your journal repo.
* [ ] Work on your first set of Coding Kata exercises.

**Comment by kdw9** [comment]
https://github.com/kdw9/kdw9.github.io/wiki/The-Right-Mindset

**Comment by jcgohlke** [comment]
Good job. Please review and close.
