### ISSUE TITLE
22 -- Dude, Where's My Car? -- Elizabeth Elliott

### ISSUE THREAD

**Issue by Za1006** [TheIronYard--Orlando/2015--FALL--iOS#213]
#### Normal Mode

* [x] Create a view controller that shows a navigation bar.
* [x] Add a UIMapView to the view controller's view. Make it span the entire view.
* [x] Add a button (possibly in the navbar?) to allow the user to drop a pin at their current location.
* [ ] Set up your view controller to track the user's current location.
* [ ] Create an object to model a particular location and the title or description the user entered for that location.
    * [x] Configure the above object to be encoded/decoded using NSCoding.
* [ ] Add code to the AppDelegate to allow for encoding/decoding on shutdown/launch.
* [ ] Configure the view controller to pull the data in from NSUserDefaults if it exists, and then display the pin on the map.

#### Hard Mode

* [ ] Find the user's current location and drop a pin
* [ ] Determine walking directions between the user's current location and the location of their car.
    * [ ] Display this route as an overlay path between the two pins.
    * [ ] Add label(s) on top of the map that shows the estimated time of arrival, the distance from the user to their car, and the travel time.

#### Kata 4

* [ ] Continue work on Kata 4.

**Comment by jholsapple** [comment]
No pull request
