### ISSUE TITLE
01 -- Great-Scott -- Samuel Shaw

### ISSUE THREAD

**Issue by SamuelShaw** [TheIronYard--Orlando/2015--FALL--iOS#22]
### Shaving the Weekly Yak
* [X] Complete the repo-related tasks for your weekly journal (see below).
* [X] Commit and push your Counter app prework to your TIY-Assignments folder.
* [X] Begin research on The Right Mindset.
* [X] Complete either an outline or (very) rough draft of your essay and place in your journal repo's wiki.
* [ ] Work on your first set of Coding Kata exercises.

**Comment by SamuelShaw** [comment]
## **Samuel Shaw, The Right Mindset Wiki**
https://github.com/SamuelShaw/SamuelShaw.github.io.wiki.git

**Comment by jcgohlke** [comment]
Good job. Please review and close.
