### ISSUE TITLE
01-- Great Scott! Elizabeth Elliott

### ISSUE THREAD

**Issue by Za1006** [TheIronYard--Orlando/2015--FALL--iOS#23]

**Comment by Za1006** [comment]
### Shaving the Weekly Yak
* [ ] Complete the repo-related tasks for your weekly journal (see below).
* [ ] Commit and push your Counter app prework to your TIY-Assignments folder.
* [ ] Begin research on The Right Mindset.
* [ ] Complete either an outline or (very) rough draft of your essay and place in your journal repo's wiki.
* [ ] Work on your first set of Coding Kata exercises.

**Comment by Za1006** [comment]
https://github.com/Za1006/Za1006.github.io/wiki/The-Right-Mindset

**Comment by jcgohlke** [comment]
Good job. Please review and close.
