### ISSUE TITLE
02 -- Human -- Samuel Shaw

### ISSUE THREAD

**Issue by SamuelShaw** [TheIronYard--Orlando/2015--FALL--iOS#24]
### Normal Mode

* [X] Create a Playground named Human.
* [X] Make a class named BodyPart.
* [X] Create 20 classes that are subclasses of BodyPart.
* [X] Each class should have 3 methods that are specific to that part.
* [X] Each class should have 3 properties that are specific to that part.

### Hard Mode

* [ ] Connect the body parts through properties.
* [ ] Tell 15 parts to do something from another part... bonus if you can chain 4 + parts through method

**Comment by SamuelShaw** [comment]
https://github.com/SamuelShaw/TIY-Assignments.git

**Comment by jcgohlke** [comment]
Good job on the subclasses. The function for each class belongs inside the {} for that class.
