### ISSUE TITLE
02 -- Human -- Jen Hamilton

### ISSUE THREAD

**Issue by embryoconcepts** [TheIronYard--Orlando/2015--FALL--iOS#25]
### Normal Mode

* [x] Create a Playground named Human. (S)
* [x] Make a class named BodyPart. (S)
* [x] Create 20 classes that are subclasses of BodyPart. (M)
* [x] Each class should have 3 methods that are specific to that part. (L)
* [x] Each class should have 3 properties that are specific to that part. (L)

### Hard Mode

* [ ] Connect the body parts through properties. (XL)
* [ ] Tell 15 parts to do something from another part... bonus if you can chain 4 + parts through methods. (XL)

**Comment by jholsapple** [comment]
Good job. Next time please assign a link to the project.
