### ISSUE TITLE
02 -- Human -- Michael Reynolds

### ISSUE THREAD

**Issue by MTR2D2** [TheIronYard--Orlando/2015--FALL--iOS#26]
### Normal Mode

* [x] Create a Playground named Human. S
* [x] Make a class named BodyPart. S
* [x] Create 20 classes that are subclasses of BodyPart. S
* [x] Each class should have 3 methods that are specific to that part. M
* [x] Each class should have 3 properties that are specific to that part. M

### Hard Mode

* [ ] Connect the body parts through properties. XL
* [ ] Tell 15 parts to do something from another part... bonus if you can chain 4 + parts through methods. XL

**Comment by MTR2D2** [comment]
https://github.com/MTR2D2/TIY-Assignments

**Comment by jholsapple** [comment]
Excellent!
