### ISSUE TITLE
29 -- Movie Mania -- Phillip English & Michael Reynolds

### ISSUE THREAD

**Issue by PhillipEnglish** [TheIronYard--Orlando/2015--FALL--iOS#262]
Pull Request: https://github.com/PhillipEnglish/TIY-Assignments/pull/16

- [x] Design Mockup (M)
- [x] Make Bigger Checklist (P)
- [x] Implement API Search (P)
- [x] Delegate Search Info to Collection View (P)
- [x] Create Data Model for Search Result (P)
- [x] Display Data in a Detail VC (P)
- [ ] Clean up autolayout (M)

**Comment by MTR2D2** [comment]
![slack for ios upload](https://cloud.githubusercontent.com/assets/12094297/11130700/5dddb4d2-8954-11e5-88b2-6933b3c93644.jpg)

Mockup

**Comment by jholsapple** [comment]
Try rotating the image ^ next time so I don't look like I'm eating a taco. Lol! Also, are you having issues with auto layout?
