### ISSUE TITLE
32 -- Global Time -- David Johnson

### ISSUE THREAD

**Issue by daaavid** [TheIronYard--Orlando/2015--FALL--iOS#269]
### Normal Mode

* [x] Using the custom clockView class we created in class today, build a tableview-based app that allows the user to select a timezone from a list of all timezones and then display an appropriate clock in a tableviewcell. Show the clock on the left and the timezone in the center of the cell.

### Hard Mode

* [x] Change the face of the clock based on the time. If it is after dark, make the face black or some other dark color. Change it back to white or a light color after sunrise (don't worry about actual sunrise/set times, just pick sensible times).

* [x] Add the ability to remove clock cells from the table. You will need to deactivate the animationTimer in the clockView class. Look at the documentation for ```CADisplayLink``` to see how to do that.

### Nightmare Mode

* [x] Nope

### Journal

Continue work on your journal. Ideally, it should be a few paragraphs in length.

**Comment by daaavid** [comment]
[Assignment](https://github.com/daaavid/TIY-Assignments/pull/32)

**Comment by jholsapple** [comment]
Awesome!

**Comment by daaavid** [comment]
Thanks!
