### ISSUE TITLE
02 -- Human -- Isaiah Khan

### ISSUE THREAD

**Issue by CodeKhan01** [TheIronYard--Orlando/2015--FALL--iOS#27]

**Comment by CodeKhan01** [comment]
### Normal Mode

* [ ] Create a Playground named Human.
* [ ] Make a class named BodyPart.
* [ ] Create 20 classes that are subclasses of BodyPart.
* [ ] Each class should have 3 methods that are specific to that part.
* [ ] Each class should have 3 properties that are specific to that part.

### Hard Mode

* [ ] Connect the body parts through properties.
* [ ] Tell 15 parts to do something from another part... bonus if you can chain 4 + parts through methods.

**Comment by jholsapple** [comment]
Try to get the last two checklist items completed.
