### ISSUE TITLE
01 -- Great Scott! -- Juan Burgos

### ISSUE THREAD

**Issue by juanburgos** [TheIronYard--Orlando/2015--FALL--iOS#28]
### Shaving the Weekly Yak
* [x] Complete the repo-related tasks for your weekly journal (see below).
* [x] Commit and push your Counter app prework to your TIY-Assignments folder.
* [x] Begin research on The Right Mindset.
* [x] Complete either an outline or (very) rough draft of your essay and place in your journal repo's wiki.
* [x] Work on your first set of Coding Kata exercises.

**Comment by jcgohlke** [comment]
Please add a link to your journal repo wiki.

**Comment by jcgohlke** [comment]
Good job on the rough draft. Please review and close after you add the link.

**Comment by juanburgos** [comment]
https://github.com/juanburgos/juanburgos.github.io/wiki/The-Right-Mindset
