### ISSUE TITLE
34 -- Contacts - Michael Reynolds

### ISSUE THREAD

**Issue by MTR2D2** [TheIronYard--Orlando/2015--FALL--iOS#284]
Normal Mode

Build a tableview (or collectionview) based app that allows the user to add contacts to a list. Collect the name, phone number and birthday (plus anything else you want) when the user creates a new contact. Also create relationships that allow for the contact to have "family" and "friends". Use Realm to create a "Contact" or similar object. You'll need a view controller to show a list of contacts, a detail view to show the contact details and an "add contact" view controller to add a new contact. Be sure to add at least 15 contacts.

Hard Mode

Break up your contacts into sections and research how to add an index to the tableview to allow the user to jump to a particular section.

Journal

Finish up your journal and place the pull request link for it in today's homework issue.

Feel free to also submit your journal entry to your new portfolio site. 😀

Portfolio

Begin to compile details for the apps you'd like to show on your portfolio site. Take some screenshots (⌘-s on the simulator) of the app running and add entries to the portfolio section. Be sure to link out to the relevant portion of your GitHub repo in the details so visitors to your site can see your work.

**Comment by MTR2D2** [comment]
https://github.com/MTR2D2/TIY-Assignments/pull/16

**Comment by MTR2D2** [comment]
Forking Practice https://github.com/TheIronYard--Orlando/2015--FALL--iOS/pull/286

**Comment by kdw9** [comment]
Money Mike you mind proof reading my journal?
github.com/kdw9/kdw9.github.io/pull/4

**Comment by MTR2D2** [comment]
Sure, but where is it? How do I see it?

**Comment by kdw9** [comment]
copy and paste this is your browser (github.com/kdw9/kdw9.github.io/pull/4), the click in the journal 4 entry download it and you can read it its a word file.

**Comment by MTR2D2** [comment]
Got it ;)

**Comment by MTR2D2** [comment]
Journal 7

https://github.com/MTR2D2/MTR2D2.github.io/pull/4

**Comment by kdw9** [comment]
Bro your writing skills is tight work. #winning

**Comment by MTR2D2** [comment]
Thanks mate. You want to edit?

**Comment by kdw9** [comment]
There's nothing that needs to be done

**Comment by MTR2D2** [comment]
haha alright
