### ISSUE TITLE
02 -- Human -- Juan Burgos

### ISSUE THREAD

**Issue by juanburgos** [TheIronYard--Orlando/2015--FALL--iOS#29]
### Normal Mode

* [x] Create a Playground named Human.
* [x] Make a class named BodyPart.
* [x] Create 20 classes that are subclasses of BodyPart.
* [x] Each class should have 3 methods that are specific to that part.
* [x] Each class should have 3 properties that are specific to that part.

### Hard Mode

* [ ] Connect the body parts through properties.
* [ ] Tell 15 parts to do something from another part... bonus if you can chain 4 + parts through methods.

**Comment by jholsapple** [comment]
Good job. You got the right idea, you just need to make sure the functions are outside the {} and not inside. Also, add a link to the project.

**Comment by juanburgos** [comment]
Fixed problems pointed by **jholsapple**

https://github.com/juanburgos/TIY-Assignments/pull/3
