### ISSUE TITLE
00 -- This is Heavy -- Elizabeth Elliott

### ISSUE THREAD

**Issue by Za1006** [TheIronYard--Orlando/2015--FALL--iOS#3]
* [X] [Create a Github account](https://github.com/signup)
* [X] Find and star [the class project](https://github.com/TheIronYard--Orlando/2015--FALL--iOS)
* [X] Read [the Home page on the class wiki](https://github.com/TheIronYard--Orlando/2015--FALL--iOS/wiki)
* [X] [Create a new _WIP Issue_](https://github.com/TheIronYard--Orlando/2015--FALL--iOS/issues/new)
  * [X] Named `00 -- This is Heavy -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  * [X] With this checklist as the description
* [X] [Edit your Github profile](https://github.com/settings/profile) to provide:
  * [X] A picture, so I can recognize your face.
  * [X] Your full name, so I can recognize your name.
  * [X] A valid public email address, so I can contact you if I need to.
* [X] [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/)
  * [X] Add a link to your new Github repo as a comment on your *WIP Issue*
* [X] Complete the Code School course [Try Git](https://www.codeschool.com/courses/try-git)
  * [X] Take a screenshot of the Try Git course when you complete it and add it as a comment to your *WIP Issue*
* [X] Create a new repository called `TIY-Assignments`
  * [X] Check the box to create an initial `README.md` file
  * [X] Select the `CC0` -- "Creative Commons" license for your work
  * [X] Add a link to your `TIY-Assignments` repo as a comment on your *WIP Issue*
* [X] Install Xcode from the Mac App Store. Simply search for _Xcode_.
* [X] Open Xcode. Click the _Xcode_ menu in the menubar, then choose _Preferences_. Navigate to the _Downloads_ tab and install the latest iOS documentation (currently iOS 8.3, will probably be 9.0 when class starts). Once fully downloaded, the docset should have a small checkmark next to it.
* [X] Watch _The Long Run_ Videos on [Delve.tv](http://delve.tv)
   * [X] [_The Long Game_, part 1](http://delve.tv/the-long-game-part-one/)
   * [x] [_The Long Game_, part 2](http://delve.tv/the-long-game-part-2/)
* [x] Complete the [Swift Basics](http://teamtreehouse.com/library/swift-basics) course on Treehouse.
   * [x] Take a screenshot of your points earned for the course and add it as a comment to your *WIP Issue*
* [x] Look at the Prework-A file for instructions on how to complete the Counter app.
   * [ ] Your counter app files should be added to your TIY-Assignments repo. Because you previously added a link to your repo to your *WIP Issue*, I will be able to see your progress as you go. Be sure to commit/push the changes you make as you work on the app.

**Comment by jcgohlke** [comment]
I made a few small changes to the Counter app files to make them compatible with Swift 2 and Xcode 7. Please be sure to update your clone of this repo on your machine before attempting.

**Comment by Za1006** [comment]
@jcgohlke I can't seem to have Xcode open the file to move forward. I am not sure if it has to do with my Mac version...took a screen shot.
![screen shot 2015-09-30 at 5 42 41 pm](https://cloud.githubusercontent.com/assets/14824381/10207543/fea03254-679a-11e5-9c6e-fa22a361fe95.png)

**Comment by Za1006** [comment]
https://github.com/Za1006/hello-world.git

**Comment by Za1006** [comment]
https://github.com/Za1006/TIY-Assignments.git

**Comment by Za1006** [comment]
![github](https://cloud.githubusercontent.com/assets/14824381/10208706/30872fc2-67a3-11e5-9e32-5aebf8e5c36c.png)

**Comment by Za1006** [comment]
![swift basic](https://cloud.githubusercontent.com/assets/14824381/10208726/5c152356-67a3-11e5-9c6a-ce54aec16ff6.png)

**Comment by jcgohlke** [comment]
@Za1006, are you running Xcode 7?

**Comment by Za1006** [comment]
@jcgohlke , I believe so.
![screen shot 2015-10-01 at 12 12 17 pm](https://cloud.githubusercontent.com/assets/14824381/10226503/d290cea8-6835-11e5-92cc-240fa1c944a9.png)

**Comment by jcgohlke** [comment]
How did you get the counter app files to your computer? Did you clone this repo?

**Comment by jcgohlke** [comment]
If you don't have the repo on your machine, click the button "download zip" to get a copy of the repo downloaded to your machine. It will appear in your downloads folder. Then, open the finder and navigate to the folder and look for the Counter app folder. Click on the .xcodeproj and it should open.

<img width="1056" alt="screen shot 2015-10-01 at 12 40 09" src="https://cloud.githubusercontent.com/assets/3697689/10227231/166f29f4-683a-11e5-9850-d8e84fd50436.png">

**Comment by Za1006** [comment]
@jcgohlke Got it! Thank you much!

**Comment by jcgohlke** [comment]
Good job. Please review this issue and close it.
