### ISSUE TITLE
02 -- Human --Elizaebth Elliott

### ISSUE THREAD

**Issue by Za1006** [TheIronYard--Orlando/2015--FALL--iOS#30]
### Normal Mode

* [x] Create a Playground named Human.(S)
* [x] Make a class named BodyPart.(S)
* [x] Create 20 classes that are subclasses of BodyPart.(XL)
* [x] Each class should have 3 methods that are specific to that part.(XL)
* [x] Each class should have 3 properties that are specific to that part.(XL)

### Hard Mode

* [ ] Connect the body parts through properties.
* [ ] Tell 15 parts to do something from another part... bonus if you can chain 4 + parts through methods.

**Comment by jholsapple** [comment]
Good job. Make sure to include two more functions and a closing } after the function. Also, don't forget a link to the project in the comments when posting the issue.

**Comment by Za1006** [comment]
https://github.com/Za1006/TIY-Assignments
