### ISSUE TITLE
02--Human--Chris Stomp

### ISSUE THREAD

**Issue by stomp1128** [TheIronYard--Orlando/2015--FALL--iOS#31]
### Normal Mode

* [x] Create a Playground named Human.
* [x] Make a class named BodyPart.
* [x] Create 20 classes that are subclasses of BodyPart.
* [x] Each class should have 3 methods that are specific to that part.
* [x] Each class should have 3 properties that are specific to that part.

### Hard Mode

* [ ] Connect the body parts through properties.
* [ ] Tell 15 parts to do something from another part... bonus if you can chain 4 + parts through methods.

**Comment by jholsapple** [comment]
Good job! Make sure to include a link to the project in the comments when posting the issue.
