### ISSUE TITLE
02 -- Human -- David Johnson

### ISSUE THREAD

**Issue by daaavid** [TheIronYard--Orlando/2015--FALL--iOS#32]
### Normal Mode

* [x] Create a Playground named Human.
* [x] Make a class named BodyPart.
* [x] Create 20 classes that are subclasses of BodyPart.
* [x] Each class should have 3 methods that are specific to that part.
* [x] Each class should have 3 properties that are specific to that part.

### Hard Mode

* [ ] Connect the body parts through properties.
* [ ] Tell 15 parts to do something from another part... bonus if you can chain 4 + parts through methods.

**Comment by daaavid** [comment]
https://github.com/daaavid/TIY-Assignments

**Comment by jholsapple** [comment]
Good job. You've got the right idea. Just remember your initializers.
