### ISSUE TITLE
43 -- Background Tunes -- Elizabeth Elliott

### ISSUE THREAD

**Issue by Za1006** [TheIronYard--Orlando/2015--FALL--iOS#332]
### Normal Mode

* [ ] Add background audio capability to the Iron Tunes project.

* [ ] Also take a look at the above documentation.

### Hard Mode

* [ ] Add code to allow Control Center to manipulate the app's playlist and also display the current track's title and artist.

* [ ] See this Apple documentation for how to use the MPNowPlayingInfoCenter to set up Control Center.

**Comment by Za1006** [comment]
https://github.com/Za1006/TIY-Assignments/pull/22

**Comment by Za1006** [comment]
Missed class that day...still trying to catch up with this assignment :(

**Comment by jholsapple** [comment]
Go ahead and close out the issue. I would recommend working on this later just to keep your assignments repo buttoned up.
