### ISSUE TITLE
02 -- Human -- Keron Williams

### ISSUE THREAD

**Issue by kdw9** [TheIronYard--Orlando/2015--FALL--iOS#34]
### Normal Mode

* [x] Create a Playground named Human.
* [x] Make a class named BodyPart.
* [x] Create 20 classes that are subclasses of BodyPart.
* [x] Each class should have 3 methods that are specific to that part.
* [x] Each class should have 3 properties that are specific to that part.

### Hard Mode

* [ ] Connect the body parts through properties.
* [ ] Tell 15 parts to do something from another part... bonus if you can chain 4 + parts through methods.

**Comment by jholsapple** [comment]
Good job. On the right track. Just remember to declare your properties as a BOOL, String, etc... and don't forget your initializer. 

Also, remember the link to your project when creating the issue.
