### ISSUE TITLE
02 -- Human -- Pedro Trujillo

### ISSUE THREAD

**Issue by PedroTrujilloV** [TheIronYard--Orlando/2015--FALL--iOS#35]
### Normal Mode

* [x] Create a Playground named Human.
* [x] Make a class named BodyPart.
* [ ] Create 20 classes that are subclasses of BodyPart.
* [x] Each class should have 3 methods that are specific to that part.
* [x] Each class should have 3 properties that are specific to that part.

### Hard Mode

* [x] Connect the body parts through properties.
* [x] Tell 15 parts to do something from another part... bonus if you can chain 4 + parts through methods.

**Comment by PedroTrujilloV** [comment]
https://github.com/PedroTrujilloV/TIY-Assignments/tree/master/02--Fourth-Dimensionally/Human/Human.playground

**Comment by PedroTrujilloV** [comment]
I'm applying  all  topics of the check boxes, but not for 20 or 15 classes asked yet

**Comment by PedroTrujilloV** [comment]
15 subparts interconnected, 4 in a torso by methods.

**Comment by jholsapple** [comment]
Good Job!
