### ISSUE TITLE
03 -- Good Morning Agent Hunt -- Samuel Shaw

### ISSUE THREAD

**Issue by SamuelShaw** [TheIronYard--Orlando/2015--FALL--iOS#36]
#### Storyboard Tasks
* [X] Add two UITextFields to the top of the view. Have them stretch to 80% of their superview's width.
* [X] Add a button centered below the textfields. The title should read "Authenticate".
* [X] Add a centered label below the button.
* [X] Place a UITextView below the label. It should also stretch to 80% of its superview's width (hint: you can instead use a constraint to make it the same width as one of the textfields, which will have the same effect).
* [X] Add a UIImageView and set it to the TIY logo image from your image assets. It should be centered with the rest of the elements.

#### Code Changes

* [X] 1. Copy the MissionBriefingViewControler.swift file into your project, and delete the ViewConroller.swift file that Xcode created for you.
* [X] 2. Change the class name of the view in the storyboard to match the class you just imported.
* [X] 3. The UI elements should be set to an "empty string" in viewDidLoad of the ViewController class.
* [ ] 4. The code should check to ensure BOTH the agent name and password fields are nonempty before allowing authentication.
* [ ] 5. The greeting label should display "Good evening, Agent [last name]", where the agent's last name is pulled from the textfield.
* [ ] 6. The mission briefing should display the information from MissionBriefing.txt (copy-paste, you don't have to read from the file). It also contains a placeholder for the agent's last name.
* [ ] 7. The background color of the view should change to green on successful authentication of the agent.
* [ ] 8. The background color of the view should change to red to indicate a failed login of the agent.

### Hard Mode
* [ ] Modify the constraints on the imageview (and possibly other views) to cause the logo to shrink

**Comment by jholsapple** [comment]
Keep working on it. This is a good project for getting a lot of the basics down. Remember to add a link to the project when creating the issue.
