### ISSUE TITLE
03 -- Good Morning, Agent Hunt -- Pedro Trujillo

### ISSUE THREAD

**Issue by PedroTrujilloV** [TheIronYard--Orlando/2015--FALL--iOS#42]
#### Storyboard Tasks
* [x] Add two UITextFields to the top of the view. Have them stretch to 80% of their superview's width.
* [x] Add a button centered below the textfields. The title should read "Authenticate".
* [x] Add a centered label below the button.
* [x] Place a UITextView below the label. It should also stretch to 80% of its superview's width (hint: you can instead use a constraint to make it the same width as one of the textfields, which will have the same effect).
* [x] Add a UIImageView and set it to the TIY logo image from your image assets. It should be centered with the rest of the elements.

#### Code Changes

* [x] 1. Copy the MissionBriefingViewControler.swift file into your project, and delete the ViewConroller.swift file that Xcode created for you.
* [x] 2. Change the class name of the view in the storyboard to match the class you just imported.
* [x] 3. The UI elements should be set to an "empty string" in viewDidLoad of the ViewController class.
* [x] 4. The code should check to ensure BOTH the agent name and password fields are nonempty before allowing authentication.
* [x] 5. The greeting label should display "Good evening, Agent [last name]", where the agent's last name is pulled from the textfield.
* [x] 6. The mission briefing should display the information from MissionBriefing.txt (copy-paste, you don't have to read from the file). It also contains a placeholder for the agent's last name.
* [x] 7. The background color of the view should change to green on successful authentication of the agent.
* [x] 8. The background color of the view should change to red to indicate a failed login of the agent.

### Hard Mode
* [ ] Modify the constraints on the imageview (and possibly other views) to cause the logo to shrink when switching to landscape orientation (the current constraints cause it to float off the bottom of the viewable screen).

**Comment by PedroTrujilloV** [comment]
https://github.com/PedroTrujilloV/TIY-Assignments/tree/master/03--Good-Morning-Agent-Hunt/MissionBriefing

**Comment by PedroTrujilloV** [comment]
Fixing bugs related with Outlets

**Comment by jholsapple** [comment]
Good job!

**Comment by PedroTrujilloV** [comment]
Thanks!
