### ISSUE TITLE
00 -- This is Heavy -- Samuel

### ISSUE THREAD

**Issue by SamuelShaw** [TheIronYard--Orlando/2015--FALL--iOS#5]
* [X] [Create a Github account](https://github.com/signup)
* [X] Find and star [the class project](https://github.com/TheIronYard--Orlando/2015--FALL--iOS)
* [X] Read [the Home page on the class wiki](https://github.com/TheIronYard--Orlando/2015--FALL--iOS/wiki)
* [X] [Create a new _WIP Issue_](https://github.com/TheIronYard--Orlando/2015--FALL--iOS/issues/new)
  * [X] Named `00 -- This is Heavy -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  * [X] With this checklist as the description
* [X] [Edit your Github profile](https://github.com/settings/profile) to provide:
  * [X] A picture, so I can recognize your face.
  * [X] Your full name, so I can recognize your name.
  * [X] A valid public email address, so I can contact you if I need to.
* [X] [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/)
  * [X] Add a link to your new Github repo as a comment on your *WIP Issue*
* [X] Complete the Code School course [Try Git](https://www.codeschool.com/courses/try-git)
  * [X] Take a screenshot of the Try Git course when you complete it and add it as a comment to your *WIP Issue*
* [X] Create a new repository called `TIY-Assignments`
  * [X] Check the box to create an initial `README.md` file
  * [X] Select the `CC0` -- "Creative Commons" license for your work
  * [X] Add a link to your `TIY-Assignments` repo as a comment on your *WIP Issue*
* [X] Install Xcode from the Mac App Store. Simply search for _Xcode_.
* [X] Open Xcode. Click the _Xcode_ menu in the menubar, then choose _Preferences_. Navigate to the _Downloads_ tab and install the latest iOS documentation (currently iOS 8.3, will probably be 9.0 when class starts). Once fully downloaded, the docset should have a small checkmark next to it.
* [X] Watch _The Long Run_ Videos on [Delve.tv](http://delve.tv)
   * [X] [_The Long Game_, part 1](http://delve.tv/the-long-game-part-one/)
   * [X] [_The Long Game_, part 2](http://delve.tv/the-long-game-part-2/)
* [X] Complete the [Swift Basics](http://teamtreehouse.com/library/swift-basics) course on Treehouse.
   * [X] Take a screenshot of your points earned for the course and add it as a comment to your *WIP Issue*
* [ ] Look at the Prework-A file for instructions on how to complete the Counter app.
   * [ ] Your counter app files should be added to your TIY-Assignments repo. Because you previously added a link to your repo to your *WIP Issue*, I will be able to see your progress as you go. Be sure to commit/push the changes you make as you work on the app.

**Comment by SamuelShaw** [comment]
https://github.com/SamuelShaw/hello-world.git

**Comment by SamuelShaw** [comment]
![screen shot 2015-09-28 at 1 31 07 am](https://cloud.githubusercontent.com/assets/14863465/10128434/b83dca54-6580-11e5-9490-ae810a62ad93.png)

**Comment by SamuelShaw** [comment]
https://github.com/SamuelShaw/TIY-Assignments.git

**Comment by jcgohlke** [comment]
I made a few small changes to the Counter app files to make them compatible with Swift 2 and Xcode 7. Please be sure to update your clone of this repo on your machine before attempting.

**Comment by SamuelShaw** [comment]
![screen shot 2015-10-01 at 4 10 03 pm](https://cloud.githubusercontent.com/assets/14863465/10232494/14b24f70-6857-11e5-9d1e-bde141cdc8b9.png)
Had trouble with the output simulator on some of the review questions.. but got through the course. I'll be reviewing control and flow

**Comment by jcgohlke** [comment]
Most of the tasks are completed, but the Counter app is missing some key lines of code to allow it to function. It's important to keep up with the current assignment, so please only revisit this if you have extra time. Please review and close this issue.
