### ISSUE TITLE
00 -- This is Heavy -- Chris Stomp

### ISSUE THREAD

**Issue by stomp1128** [TheIronYard--Orlando/2015--FALL--iOS#7]
### Tasks:

* [X] [Create a Github account](https://github.com/signup)
* [X] Find and star [the class project](https://github.com/TheIronYard--Orlando/2015--FALL--iOS)
* [x] Read [the Home page on the class wiki](https://github.com/TheIronYard--Orlando/2015--FALL--iOS/wiki)
* [x] [Create a new _WIP Issue_](https://github.com/TheIronYard--Orlando/2015--FALL--iOS/issues/new)
  * [x] Named `00 -- This is Heavy -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  * [x] With this checklist as the description
* [x] [Edit your Github profile](https://github.com/settings/profile) to provide:
  * [x] A picture, so I can recognize your face.
  * [x] Your full name, so I can recognize your name.
  * [x] A valid public email address, so I can contact you if I need to.
* [x] [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/)
  * [x] Add a link to your new Github repo as a comment on your *WIP Issue*
* [x] Complete the Code School course [Try Git](https://www.codeschool.com/courses/try-git)
  * [x] Take a screenshot of the Try Git course when you complete it and add it as a comment to your *WIP Issue*
* [x] Create a new repository called `TIY-Assignments`
  * [x] Check the box to create an initial `README.md` file
  * [x] Select the `CC0` -- "Creative Commons" license for your work
  * [x] Add a link to your `TIY-Assignments` repo as a comment on your *WIP Issue*
* [x] Install Xcode from the Mac App Store. Simply search for _Xcode_.
* [x] Open Xcode. Click the _Xcode_ menu in the menubar, then choose _Preferences_. Navigate to the _Downloads_ tab and install the latest iOS documentation (currently iOS 8.3, will probably be 9.0 when class starts). Once fully downloaded, the docset should have a small checkmark next to it.
* [x] Watch _The Long Run_ Videos on [Delve.tv](http://delve.tv)
   * [x] [_The Long Game_, part 1](http://delve.tv/the-long-game-part-one/)
   * [x] [_The Long Game_, part 2](http://delve.tv/the-long-game-part-2/)
* [x] Complete the [Swift Basics](http://teamtreehouse.com/library/swift-basics) course on Treehouse.
   * [x] Take a screenshot of your points earned for the course and add it as a comment to your *WIP Issue*
* [x] Look at the Prework-A file for instructions on how to complete the Counter app.
   * [x] Your counter app files should be added to your TIY-Assignments repo. Because you previously added a link to your repo to your *WIP Issue*, I will be able to see your progress as you go. Be sure to commit/push the changes you make as you work on the app.

**Comment by stomp1128** [comment]
https://github.com/stomp1128/hello-world

**Comment by stomp1128** [comment]
![screen shot 2015-09-30 at 5 25 32 pm](https://cloud.githubusercontent.com/assets/14911933/10207118/75acfeb6-6798-11e5-9453-ae08eb3b0d7c.png)

**Comment by stomp1128** [comment]
https://github.com/stomp1128/TIY-Assignments.git

**Comment by stomp1128** [comment]
![screen shot 2015-09-30 at 6 15 16 pm](https://cloud.githubusercontent.com/assets/14911933/10208155/453495ee-679f-11e5-8750-72e889740db5.png)

**Comment by jcgohlke** [comment]
Great job. Please review and close this issue.
