### ISSUE TITLE
07 -- Jackpot -- Samuel Shaw

### ISSUE THREAD

**Issue by SamuelShaw** [TheIronYard--Orlando/2015--FALL--iOS#71]
### Grandma's Hugs & Kisses Mode
* [X] Open GitHub Desktop
* [X] Create a new branch from master in top left corner with today's assignment name "Jackpot"
* [X] Open the Xcode App
* [X] Select New Project
* [X] Name the new project file "Jackpot"
* [X] Place new file into TIY assignments folder
* [X] Commit the new project in GitHub under the created branch with the same name
* [X] Create pull request using the same name of the homework as reference.
* [X] Make a new issue for the homework under the 2015--FALL--iOS repo.
* [X] Copy the "Pull URL" inside the homework's issue in a comment.
* [X] Create a list of storyboard & code tasks
* [X] Copy task list & paste into the issue created

### Normal Mode

* [X] Create a single view application that shows a table view as its main interface to the user
* [X] Provide a Navigation Controller to handle eventual view transitions
* [X] Add an "add" button to the navigation bar 
* [X] When tapped, it will generate a quick pick lottery number and place it in a cell in the table view.

#### Journal, Week 1
   * [ ] Create a PR
   * [ ] Work on draft journal entry

**Comment by jholsapple** [comment]
Remember to post a link to the project when creating the issue.
