### ISSUE TITLE
07 -- Clean Up -- Isaiah Khan

### ISSUE THREAD

**Issue by CodeKhan01** [TheIronYard--Orlando/2015--FALL--iOS#72]
### Normal Mode

* [ ] Create a list of storyboard and code tasks

#### Journal, Week 1
   * [x] Create a PR
   * [x] Work on draft journal entry

**Comment by CodeKhan01** [comment]
https://github.com/CodeKhan01/CodeKhan01.github.io/pull/1

**Comment by CodeKhan01** [comment]
https://github.com/CodeKhan01/TIY-Assignments/pull/1

**Comment by jholsapple** [comment]
Change the name from Clean up to Jackpot and remember to post a link to the project when creating the issue. Also, you forgot most of the checklist.
