### ISSUE TITLE
07 -- Jackpot -- David Johnson 

### ISSUE THREAD

**Issue by daaavid** [TheIronYard--Orlando/2015--FALL--iOS#73]
### Normal Mode

* [x] Create a list of storyboard and code tasks
* [x] Create xcode project and delete the viewcontroller and viewcontroller swift file
* [x] Create table view controller and table view controller swift file, embed in nav controller
* [x] Add "add" button to nav bar
* [x] Make quick pick function in a ticket.swift that creates 6 integers from 1-53
* [x] Link add button and quick pick function
* [x] Make add button reload data
* [x] Set up table view to place lottery numbers in subsequent cells
* [x] Set up function to check for duplicate numbers in tickets 

#### Journal, Week 1
   * [x] Create a PR
   * [x] Work on draft journal entry

**Comment by daaavid** [comment]
https://github.com/daaavid/TIY-Assignments/pull/10

**Comment by daaavid** [comment]
Journal Draft 

https://github.com/daaavid/daaavid.github.io/pull/1

**Comment by jholsapple** [comment]
Good Job!

**Comment by daaavid** [comment]
Thanks!
