### ISSUE TITLE
07-- Jackpot -- Elizabeth Elliott

### ISSUE THREAD

**Issue by Za1006** [TheIronYard--Orlando/2015--FALL--iOS#74]
### Normal Mode

* [x] Erase view controller
* [x] Delete view controller.swift file

TableViewController:
* [x] Create a  tableview controller from the library 
* [x] Placing class name JackpotTableViewController for the tableview controller
* [x] Create .swift file and set it's class 
* [x]  Create. Ticket.swift file
* [x] Be sure view controller is set as the initial view controller
* [x] Add an "add" button 

#### Code Tasks
JackpotTableViewController: 
* [x]  Create the Outlet for the add action button.
* [x] set class for Ticket.swift file
* [x] Create QuickPick function to generate lottery number within the range 1 through 53. Picking a number does not preclude it from being picked again for another of the 6 in the sequence.

#### Journal, Week 1
   * [x] Create a PR
   * [x] Work on draft journal entry

**Comment by Za1006** [comment]
https://github.com/Za1006/TIY-Assignments/tree/Jackpot

**Comment by jholsapple** [comment]
Good job!
