### ISSUE TITLE
07-- Jackpot -- Phillip English

### ISSUE THREAD

**Issue by PhillipEnglish** [TheIronYard--Orlando/2015--FALL--iOS#76]
### Normal Mode

* [x] Create a list of storyboard and code tasks

Storyboard tasks
* [x] Remove view controller from storyboard
* [x] Create a UITableViewController
* [x] Connect custom class to the View Controller once it's created
* [x] Create a navigation controller embed in UITableViewController
* [ ] Add a menu bar with an add button in the view

Code Tasks
* [x] Delete view controller class 
* [x] Create a class for UITableView
* [ ] Write a function to generate 6 integers within the range of 1 through 53
* [ ] Make it so that the add button calls the above mentioned function when pressed
* [ ]  Update the cell view with the integers generated in the above function, and make it so that an additional cell with a new series of integers is added every time the function is called

#### Journal, Week 1
   * [x] Create a PR
   * [ ] Work on draft journal entry

**Comment by PhillipEnglish** [comment]
https://github.com/PhillipEnglish/TIY-Assignments/pull/2

**Comment by PhillipEnglish** [comment]
https://github.com/PhillipEnglish/PhillipEnglish.github.io/pull/1

**Comment by jholsapple** [comment]
Keep at it
