### ISSUE TITLE
07 -- Jackpot -- Jen Hamilton

### ISSUE THREAD

**Issue by embryoconcepts** [TheIronYard--Orlando/2015--FALL--iOS#77]
### Normal Mode
* [x] Create a list of storyboard and code tasks

#### Storyboard Tasks
* [x] Create a single view application that shows a table view as its main interface to the user.  
* [x]  Provide a Navigation Controller to handle eventual view transitions (we'll add these later).
* [x] Add an "add" button to the navigation bar that when tapped, will generate a quick pick lottery number and place it in a cell in the table view.

##### LotteryTicket()
* [x] Create a model (class) for LotteryTicket
* [x] Create a func in the LotteryTicket class that generates non-repeating random numbers and initializes with an Array of the numbers 
* [x]  Quick pick is defined as a lottery number that is randomly generated. A lottery number is 6 integers that are within the range 1 through 53. Picking a number does not preclude it from being picked again for another of the 6 in the sequence.

##### TicketTableViewController
* [x] Assign the class to the VC in the Storyboard
* [x] Add and wire an outlet for addTicket button
* [x] Create an Array to hold LotteryTicket objects
* [x] Display the Array in the Table View 
* [x] Create an addTicket() method to generate a new LotteryTicket() object and pass into an Array of LotteryTicket objects

#### Journal, Week 1
   * [x] Create a PR
   * [x] Work on draft journal entry.
Possible topics:
-  What do developers do? What principles of a developer have you learned?
-   Explain how the user experience of your app should impact how you design and construct your code. How should user-focused considerations affect your code structure?
-  Explain the branching principle in Git. Why do we branch? What does branching enable for our codebase?

**Comment by embryoconcepts** [comment]
https://github.com/embryoconcepts/TIY-Assignments/pull/8

**Comment by embryoconcepts** [comment]
Journal done, and set up in a way to demonstrate the issues that I'm experiencing branching with a wiki.
https://github.com/embryoconcepts/embryoconcepts.github.io/wiki/Journal-Week-1

**Comment by jholsapple** [comment]
Good job!
