### ISSUE TITLE
07 -- Jackpot -- Michael Reynolds

### ISSUE THREAD

**Issue by MTR2D2** [TheIronYard--Orlando/2015--FALL--iOS#78]
### Normal Mode

* [ ] Create a list of storyboard and code tasks

### Storyboard Tasks

* [x] Delete View Controller and View Controller Class
* [x] Add Table View 
* [x] Add Cocoa Class Table View Controller
* [x] Embed in a Navigation Controller
* [x] Place an "add" button into the Navigation Controller

### Code Tasks

* [ ] 
* [ ] 
* [ ] 
* [ ] 

#### Journal, Week 1
   * [x] Create a PR
   * [ ] Work on draft journal entry

**Comment by MTR2D2** [comment]
https://github.com/MTR2D2/TIY-Assignments/pull/1

**Comment by jholsapple** [comment]
Keep at it.
