### ISSUE TITLE
07 -- Jackpot -- Keron Williams

### ISSUE THREAD

**Issue by kdw9** [TheIronYard--Orlando/2015--FALL--iOS#79]
Assignment Checklist

### Xcode
* [x] Properly set up Commit method in Git Desktop

#### Storyboard Tasks
* [x] Remove the view in the storyboard from the template
* [x] Add a Table View Controller to the canvas
* [x] Embed the above in a Navigation Controller
* [x] Add an "add" button to the navigation bar 
 
#### Code Tasks
* [x] Remove the _ViewController.swift_ file from the project
* [x] Add a new Table View Controller subclass called _JackPotTableViewController_
* [x] Add a new swift class called "Money"
* [x] Create a model function
* [x] Create a function to randomly generate a quick pick lottery number with 6 integers that are within the range 1 through 53 and place it in a cell in the table view
 
#### Journal, Week 1
   * [ ] created branch in `USERNAME.github.io` named `journal-week-1`
   * [ ] created new file named `journal-week-1.md`
   * [ ] commited, pushed, and opened PR to `master`

**Comment by jholsapple** [comment]
Keep at it
