### ISSUE TITLE
07 -- Jackpot -- Juan Burgos

### ISSUE THREAD

**Issue by juanburgos** [TheIronYard--Orlando/2015--FALL--iOS#80]
07 -- Jackpot -- Juan Burgos

### Grandma's soft-batch-butter-homemade cookie Mode:
* [x] Create a new branch from _Master_ in Github with today's assignment name.
* [x] In Xcode: Create a new proyect called "Jackpot".
* [x] Commit the new proyect to Github.
* [x] Create pull request using the same name of the homework as reference.
* [x] Make a new issue for the homework under the _2015--FALL--iOS_ repo.
* [x] Copy the "Pull URL" inside the homework's issue in a comment.

### Normal Mode
* [x] In Xcode: Create a single view application that shows a table view as its main interface to the user.
	* [x] Provide a Navigation Controller to handle eventual view transitions (we'll add these later).
	* [x] Add an "add" button to the navigation bar that when tapped, will generate a quick pick lottery number and place it in a cell in the table view.
	* [x] Save all progress and close Xcode.
* [x] Commit changes to Github.

#### Journal, Week 1
* [x] Create a PR.
* [x] Work on draft journal entry.

#### Personal Development
* [x] Create an Apple Developer account.
* [x] Practice my keyboard typing skills with _keybr.com_.
* [x] Review the _Welcome To Swift_ documentation.
* [x] Backup all your work!

**Comment by juanburgos** [comment]
https://github.com/juanburgos/TIY-Assignments/pull/1

**Comment by jholsapple** [comment]
You have everything checked off, but I didn't see anything in there when i opened the project. If you have it done, make sure it's committing
